services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: construction-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: construction-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: